name: Go Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Run table-diff tests
      run: go test -count=1 -v ./tests/integration -run 'TableDiff'

    - name: Run table-repair tests
      run: go test -count=1 -v ./tests/integration -run 'TableRepair'

    - name: Run Merkle Tree tests
      run: go test -count=1 -v ./tests/integration -run 'MerkleTree'
